[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-server"
version = "0.1.0"
description = "A Model Context Protocol (MCP) server"
authors = [
    { name = "DVZolotarev", email = "your.email@mailservice.com" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp==1.16.0",
    "mcpo==0.0.17",
    "httpx==0.28.1"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=23.0",
    "isort>=5.0",
    "mypy>=1.0",
    "ruff>=0.2.0"
]

# for journal_server mcp server
journal_server = [
    "asyncpg==0.30.0",
]

# for analytics_server mcp server
analytics_server = [
    "asyncpg==0.30.0",
    "pandas>=2.2",
    "plotly>=5.18.0",
    "matplotlib>=3.8.0",
]

# for scheduler_server mcp server
scheduler_server = [
    "asyncpg==0.30.0",
    "apscheduler>=3.10.0",
]

[tool.setuptools]
packages = ["app"]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.ruff]
line-length = 88
target-version = "py311"
exclude = [".git", "__pycache__", ".mypy_cache", ".pytest_cache", "migrations", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]
